#!/usr/bin/env bash

set -e

OSL_REPO="git@github.com:AcademySoftwareFoundation/OpenShadingLanguage.git"
OSL_VERSION="v1.12.7.0"
OSL_BUILD_TYPE=${OSL_BUILD_TYPE:=Release}

SOURCE_DIR="$PWD/deps/osl"
INSTALL_DIR="$PWD/dist"

echo "Building OSL"

mkdir -p deps && true
mkdir -p dist && true

if [[ ! -e ${SOURCE_DIR} ]]; then
    git clone $OSL_REPO $SOURCE_DIR
fi

pushd $SOURCE_DIR
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" == "master" || "$BRANCH" == "main" ]]; then
  echo "Checking out ${OSL_VERSION}"
  git checkout -f ${OSL_VERSION}
else
  echo "Rebuilding..."
fi

INSTALL_PREFIX="$INSTALL_DIR" \
OSL_BUILD_TESTS=0 \
USE_PYTHON=0 \
LLVM_VERSION=14.0 \
LLVM_DIRECTORY=/usr/local/opt/llvm@14 \
MY_CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$INSTALL_DIR -DPYTHON_VERSION=3.10" \
make -j4 install

popd

echo "Finished OSL build"
