#!/usr/bin/env bash

set -e

OCIO_REPO="git@github.com:AcademySoftwareFoundation/OpenColorIO.git"
OCIO_VERSION="v2.2.0"
OCIO_BUILD_TYPE=${OCIO_BUILD_TYPE:=Release}

SOURCE_DIR="$PWD/deps/ocio"
INSTALL_DIR="$PWD/dist"

echo "Building OCIO"

mkdir -p deps && true
mkdir -p dist && true

if [[ ! -e ${SOURCE_DIR} ]]; then
    git clone $OCIO_REPO $SOURCE_DIR
fi

pushd $SOURCE_DIR

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" == "master" || "$BRANCH" == "main" ]]; then
  echo "Checking out ${OCIO_VERSION}"
  git checkout -f ${OCIO_VERSION}
else
  echo "Rebuilding..."
fi

mkdir -p build
cd build

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" -DOCIO_BUILD_APPS=OFF -DOCIO_BUILD_PYTHON=OFF -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DOCIO_BUILD_JAVA=OFF .. 
cmake --build . --config Release --target install

popd

echo "Finished OCIO build"
